// Package simt implements the SIMT track: kernels are written as ordinary Go
// functions and lowered to CUDA C, which NVRTC compiles to PTX at run time.
//
// Go's gc compiler has no pluggable code generation backend, so the route CUDA
// Rust takes -- a custom rustc backend emitting PTX -- is not open to Go. What
// Go does have, and Rust does not, is a parser and a type checker in its
// standard library. Translating a well-defined subset of Go at the source
// level gets most of the way there, and keeps kernels runnable on the CPU.
package simt

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"go/types"
	"io/fs"
	"sort"
	"strings"
)

// Transpile type-checks every Go file in fsys as one package and lowers the
// kernel function named fn to CUDA C.
func Transpile(fsys fs.FS, fn string) (string, error) {
	fset := token.NewFileSet()
	names, err := fs.Glob(fsys, "*.go")
	if err != nil {
		return "", err
	}
	if len(names) == 0 {
		return "", fmt.Errorf("simt: no Go sources found")
	}
	sort.Strings(names)

	var files []*ast.File
	for _, name := range names {
		src, err := fs.ReadFile(fsys, name)
		if err != nil {
			return "", err
		}
		f, err := parser.ParseFile(fset, name, src, parser.SkipObjectResolution)
		if err != nil {
			return "", fmt.Errorf("simt: %w", err)
		}
		files = append(files, f)
	}

	info := &types.Info{
		Types:      make(map[ast.Expr]types.TypeAndValue),
		Defs:       make(map[*ast.Ident]types.Object),
		Uses:       make(map[*ast.Ident]types.Object),
		Selections: make(map[*ast.SelectorExpr]*types.Selection),
	}
	conf := types.Config{Importer: synthImporter{gpu: gpuPackage()}}
	if _, err := conf.Check("kernels", fset, files, info); err != nil {
		return "", fmt.Errorf("simt: type error in kernel source: %w", err)
	}

	var decl *ast.FuncDecl
	for _, f := range files {
		for _, d := range f.Decls {
			if fd, ok := d.(*ast.FuncDecl); ok && fd.Name.Name == fn {
				decl = fd
			}
		}
	}
	if decl == nil {
		return "", fmt.Errorf("simt: no function %q in kernel source", fn)
	}

	t := &transpiler{fset: fset, info: info, lens: map[string]string{}}
	t.kernel(decl)
	if t.err != nil {
		return "", t.err
	}
	return t.buf.String(), nil
}

type transpiler struct {
	fset *token.FileSet
	info *types.Info
	buf  strings.Builder
	ind  int
	// lens maps a slice-valued name to the C expression giving its length.
	lens map[string]string
	err  error
}

func (t *transpiler) fail(pos token.Pos, format string, args ...any) {
	if t.err == nil {
		t.err = fmt.Errorf("simt: %s: %s", t.fset.Position(pos), fmt.Sprintf(format, args...))
	}
}

func (t *transpiler) line(format string, args ...any) {
	t.buf.WriteString(strings.Repeat("\t", t.ind))
	fmt.Fprintf(&t.buf, format, args...)
	t.buf.WriteByte('\n')
}

// kernel emits the __global__ entry point for fd.
func (t *transpiler) kernel(fd *ast.FuncDecl) {
	if fd.Recv != nil {
		t.fail(fd.Pos(), "a kernel must be a plain function, not a method")
		return
	}
	if fd.Type.Results != nil {
		t.fail(fd.Pos(), "a kernel must not return values; write results through a slice parameter")
		return
	}
	params := t.params(fd.Type.Params)
	if len(params) == 0 || !t.isCtx(params[0].typ) {
		t.fail(fd.Pos(), "a kernel's first parameter must be gpu.Ctx")
		return
	}

	var decls []string
	for _, p := range params[1:] {
		name := cname(p.name)
		switch typ := p.typ.(type) {
		case *types.Slice:
			elem := t.ctype(typ.Elem(), p.pos)
			// A Go slice carries its length; C does not, so every slice
			// parameter lowers to a pointer plus an explicit length.
			decls = append(decls, fmt.Sprintf("%s* %s", elem, name), fmt.Sprintf("int %s_len", name))
			t.lens[p.name] = name + "_len"
		default:
			decls = append(decls, fmt.Sprintf("%s %s", t.ctype(p.typ, p.pos), name))
		}
	}

	t.line("// generated by github.com/CWBudde/gocuda/simt from %s", t.fset.Position(fd.Pos()).Filename)
	t.line("extern \"C\" __global__ void %s(%s)", fd.Name.Name, strings.Join(decls, ", "))
	t.block(fd.Body)
}

type param struct {
	name string
	typ  types.Type
	pos  token.Pos
}

// params flattens a parameter list, resolving each name's checked type.
func (t *transpiler) params(fl *ast.FieldList) []param {
	var out []param
	if fl == nil {
		return out
	}
	for _, f := range fl.List {
		for _, n := range f.Names {
			obj := t.info.Defs[n]
			if obj == nil {
				t.fail(n.Pos(), "parameter %s has no resolved type", n.Name)
				return out
			}
			out = append(out, param{name: n.Name, typ: obj.Type(), pos: n.Pos()})
		}
	}
	return out
}

func (t *transpiler) isCtx(typ types.Type) bool {
	named, ok := typ.(*types.Named)
	if !ok {
		return false
	}
	obj := named.Obj()
	return obj != nil && obj.Name() == "Ctx" && obj.Pkg() != nil && obj.Pkg().Path() == GPUPkgPath
}

// ctype maps a Go type to its device counterpart.
//
// Go's int is 64-bit while CUDA's int is 32-bit. Kernel indices are bounded by
// the grid, so the narrowing is safe here and keeps generated code idiomatic;
// it is the one deliberate infidelity in the mapping.
func (t *transpiler) ctype(typ types.Type, pos token.Pos) string {
	basic, ok := typ.Underlying().(*types.Basic)
	if !ok {
		t.fail(pos, "unsupported type %s on the device", typ)
		return "void"
	}
	switch basic.Kind() {
	case types.Float32, types.UntypedFloat:
		return "float"
	case types.Int, types.Int32, types.UntypedInt:
		return "int"
	case types.Uint32:
		return "unsigned int"
	case types.Bool, types.UntypedBool:
		return "bool"
	}
	t.fail(pos, "unsupported type %s on the device (kernels are float32/int32 only)", typ)
	return "void"
}
