// generated by github.com/CWBudde/gocuda/simt from bandgain.go
struct Band
{
	float Upper;
	float Gain;
};
static_assert(sizeof(Band) == 8, "gocuda: Band is a different size in CUDA than in Go");
static_assert(alignof(Band) == 4, "gocuda: Band is differently aligned in CUDA than in Go");

struct Shape
{
	float Floor;
	int Count;
	double Bias;
};
static_assert(sizeof(Shape) == 16, "gocuda: Shape is a different size in CUDA than in Go");
static_assert(alignof(Shape) == 8, "gocuda: Shape is differently aligned in CUDA than in Go");

extern "C" __global__ void BandGain(float* __restrict__ y, int y_len, const float* __restrict__ x, int x_len, const Band* __restrict__ bands, int bands_len, Shape cfg)
{
	int i = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	if (i >= y_len)
	{
		return;
	}
	float v = x[i];
	Band best = Band{0, cfg.Floor};
	for (int b_i = 0; b_i < bands_len; b_i++)
	{
		Band b = bands[b_i];
		if (v <= b.Upper)
		{
			best = b;
			break;
		}
	}
	float taps[4] = {};
	for (int j = 0; j < 4; j++)
	{
		int k = (int)((unsigned int)(i) + (unsigned int)(j) - 2u);
		if (k >= 0 && k < x_len)
		{
			taps[j] = x[k];
		}
	}
	float sum = 0;
	for (int tv_i = 0; tv_i < 4; tv_i++)
	{
		float tv = taps[tv_i];
		sum += tv;
	}
	double acc = (double)(sum) / 4.0 * (double)(best.Gain) + cfg.Bias;
	y[i] = (float)(acc) * (float)(cfg.Count);
}
