// generated by github.com/CWBudde/simtgo/simt from classify.go
extern "C" __global__ void Classify(float* __restrict__ out, int out_len, const float* __restrict__ x, int x_len, const float* __restrict__ edges, int edges_len)
{
	int i = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	if (i >= out_len)
	{
		return;
	}
	float v = fabsf(x[i]);
	int band = edges_len;
	for (int base = 0; base < edges_len; base += 4)
	{
		for (int j = base; j < (int)((unsigned int)(base) + 4u); j++)
		{
			if (j >= edges_len)
			{
				goto search_break;
			}
			if (v <= edges[j])
			{
				band = j;
				goto search_break;
			}
		}
	}
	search_break: ;
	float gain = 0;
	switch (band)
	{
	case 0:
		{
			gain = 0.25f;
			break;
		}
	case 1:
	case 2:
		{
			gain = 0.5f;
			break;
		}
	case 3:
		{
			gain = 0.75f;
			break;
		}
	default:
		{
			gain = 1.0f;
			break;
		}
	}
	float bias = 0.0f;
	for (int e_i = 0; e_i < edges_len; e_i++)
	{
		float e = edges[e_i];
		bias += e;
	}
	out[i] = gain * v + bias * 0.001f;
}
