// generated by github.com/CWBudde/gocuda/simt from fir.go
extern "C" __global__ void FIR(float* __restrict__ y, int y_len, const float* __restrict__ x, int x_len, const float* __restrict__ h, int h_len)
{
	__shared__ float tile[320];
	int taps = h_len;
	int base = (int)blockIdx.x * (int)blockDim.x;
	int t = (int)threadIdx.x;
	for (int k = t; k < (int)blockDim.x + taps - 1; k += (int)blockDim.x)
	{
		int src = base + k - (taps - 1);
		float v = 0.0f;
		if (src >= 0 && src < x_len)
		{
			v = x[src];
		}
		tile[k] = v;
	}
	__syncthreads();
	int n = base + t;
	if (n < y_len)
	{
		float acc = 0.0f;
		for (int k = 0; k < h_len; k++)
		{
			acc += h[k] * tile[t + taps - 1 - k];
		}
		y[n] = acc;
	}
}
