// generated by github.com/CWBudde/simtgo/simt from fir.go
extern "C" __global__ void FIR(float* __restrict__ y, int y_len, const float* __restrict__ x, int x_len, const float* __restrict__ h, int h_len)
{
	__shared__ float tile[320];
	int taps = h_len;
	int base = (int)((unsigned int)((int)blockIdx.x) * (unsigned int)((int)blockDim.x));
	int t = (int)threadIdx.x;
	for (int k = t; k < (int)((unsigned int)((int)blockDim.x) + (unsigned int)(taps) - 1u); k += (int)blockDim.x)
	{
		int src = (int)((unsigned int)(base) + (unsigned int)(k) - ((unsigned int)(taps) - 1u));
		float v = 0.0f;
		if (src >= 0 && src < x_len)
		{
			v = x[src];
		}
		tile[k] = v;
	}
	__syncthreads();
	int n = (int)((unsigned int)(base) + (unsigned int)(t));
	if (n < y_len)
	{
		float acc = 0.0f;
		for (int k = 0; k < h_len; k++)
		{
			acc += h[k] * tile[(int)((unsigned int)(t) + (unsigned int)(taps) - 1u - (unsigned int)(k))];
		}
		y[n] = acc;
	}
}
