// generated by github.com/CWBudde/simtgo/simt from gray.go
extern "C" __global__ void Gray(unsigned char* __restrict__ out, int out_len, const unsigned char* __restrict__ rgb, int rgb_len)
{
	int i = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	if (i >= out_len)
	{
		return;
	}
	int j = (int)((unsigned int)(i) * 3u);
	if ((int)((unsigned int)(j) + 2u) >= rgb_len)
	{
		return;
	}
	int r = (int)(rgb[j]);
	int g = (int)(rgb[(int)((unsigned int)(j) + 1u)]);
	int b = (int)(rgb[(int)((unsigned int)(j) + 2u)]);
	int y = (int)(77u * (unsigned int)(r) + 150u * (unsigned int)(g) + 29u * (unsigned int)(b) + 128u) >> 8;
	out[i] = (unsigned char)(y);
}
