// generated by github.com/CWBudde/gocuda/simt from magnitudefast.go
// gocuda: fastmath
extern "C" __global__ void MagnitudeFast(float* __restrict__ mag, int mag_len, const float* __restrict__ re, int re_len, const float* __restrict__ im, int im_len, float scale)
{
	int i = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	if (i < mag_len)
	{
		float r_tmp = re[i];
		float m_tmp = im[i];
		float r = r_tmp;
		float m = m_tmp;
		mag[i] = sqrtf(r * r + m * m) / scale;
	}
}
