// generated by github.com/CWBudde/gocuda/simt from kernels.go
extern "C" __global__ void Magnitude(float* mag, int mag_len, float* re, int re_len, float* im, int im_len)
{
	int i = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	if (i < mag_len)
	{
		mag[i] = hypotf(re[i], im[i]);
	}
}
