// Code generated by "simtgo generate"; DO NOT EDIT.

package prebuilt

import (
	_ "embed"

	"github.com/CWBudde/simtgo/simt"
)

// BandGain reports that the kernel of that name lowered to CUDA C.
const BandGain Lowered = "BandGain"

// Classify reports that the kernel of that name lowered to CUDA C.
const Classify Lowered = "Classify"

// FIR reports that the kernel of that name lowered to CUDA C.
const FIR Lowered = "FIR"

// Gray reports that the kernel of that name lowered to CUDA C.
const Gray Lowered = "Gray"

// Histogram reports that the kernel of that name lowered to CUDA C.
const Histogram Lowered = "Histogram"

// VecAdd reports that the kernel of that name lowered to CUDA C.
const VecAdd Lowered = "VecAdd"

// Magnitude reports that the kernel of that name lowered to CUDA C.
const Magnitude Lowered = "Magnitude"

// Scale reports that the kernel of that name lowered to CUDA C.
const Scale Lowered = "Scale"

// MagnitudeFast reports that the kernel of that name lowered to CUDA C.
const MagnitudeFast Lowered = "MagnitudeFast"

// Quantize reports that the kernel of that name lowered to CUDA C.
const Quantize Lowered = "Quantize"

// Softclip reports that the kernel of that name lowered to CUDA C.
const Softclip Lowered = "Softclip"

// Transpose reports that the kernel of that name lowered to CUDA C.
const Transpose Lowered = "Transpose"

// WarpReduceSum reports that the kernel of that name lowered to CUDA C.
const WarpReduceSum Lowered = "WarpReduceSum"

//go:embed BandGain.compute_75.ptx
var ptxBandGain []byte

//go:embed Classify.compute_75.ptx
var ptxClassify []byte

//go:embed FIR.compute_75.ptx
var ptxFIR []byte

//go:embed Gray.compute_75.ptx
var ptxGray []byte

//go:embed Histogram.compute_75.ptx
var ptxHistogram []byte

//go:embed VecAdd.compute_75.ptx
var ptxVecAdd []byte

//go:embed Magnitude.compute_75.ptx
var ptxMagnitude []byte

//go:embed Scale.compute_75.ptx
var ptxScale []byte

//go:embed MagnitudeFast.compute_75.ptx
var ptxMagnitudeFast []byte

//go:embed Quantize.compute_75.ptx
var ptxQuantize []byte

//go:embed Softclip.compute_75.ptx
var ptxSoftclip []byte

//go:embed Transpose.compute_75.ptx
var ptxTranspose []byte

//go:embed WarpReduceSum.compute_75.ptx
var ptxWarpReduceSum []byte

func init() {
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:         "BandGain",
		SourceSHA256: "f7aa8f8064789b56f19dc6fdbdb880a4b0a9c8c611a1c514eb409820c9e38a6e",
		Arch:         "compute_75",
		PTX:          ptxBandGain,
	})
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:         "Classify",
		SourceSHA256: "0d2c2aae24716c6815acb6a4ac50955d3096f0700586291810239049d4a2af93",
		Arch:         "compute_75",
		PTX:          ptxClassify,
	})
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:          "FIR",
		SourceSHA256:  "f99a8920d257f45e777404c17538eb019ce58835c567f1bd39afe3a8314a279c",
		Arch:          "compute_75",
		PTX:           ptxFIR,
		RequiredBlock: 256,
		SharedBytes:   1280,
	})
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:         "Gray",
		SourceSHA256: "62c1897b9d1772839e66264b93a0dbaed71ffbe0375f2dda548bf1ed5f4515d6",
		Arch:         "compute_75",
		PTX:          ptxGray,
	})
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:         "Histogram",
		SourceSHA256: "41df05977a37714ed8a31459f5568418ad040175848eaecab64b6cac9418691a",
		Arch:         "compute_75",
		PTX:          ptxHistogram,
		SharedBytes:  1024,
	})
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:         "VecAdd",
		SourceSHA256: "b311b6d24deff2f0c926156b8745d5f4a4daa003c7c6109e96ebb136209664ec",
		Arch:         "compute_75",
		PTX:          ptxVecAdd,
	})
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:         "Magnitude",
		SourceSHA256: "9f2777e7f76b9f468a5541780266ffe5a81e8f5f40ca4a3ecaba94ca6bba90a1",
		Arch:         "compute_75",
		PTX:          ptxMagnitude,
	})
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:         "Scale",
		SourceSHA256: "8e523f96a72e738e2852105bf034e6f31652d41fb5a212e244c0d4286853f5ff",
		Arch:         "compute_75",
		PTX:          ptxScale,
	})
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:         "MagnitudeFast",
		SourceSHA256: "aa3ed79c40b264a913e3752399eae464599a5d59112b5b45cba91fa89aaaeae2",
		Arch:         "compute_75",
		PTX:          ptxMagnitudeFast,
	})
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:         "Quantize",
		SourceSHA256: "1e38909e1d922754bda3e614c74601b57fbc753f678f4126826ab34f7e2453c8",
		Arch:         "compute_75",
		PTX:          ptxQuantize,
	})
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:         "Softclip",
		SourceSHA256: "ac0ae2309a922cf79f8a697e949a94f816e4eb07b7f7767d3eaf77d1f0616362",
		Arch:         "compute_75",
		PTX:          ptxSoftclip,
	})
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:          "Transpose",
		SourceSHA256:  "b0010795ff8f1caa17cc61a50686a2c2763593c6766b8b1e33bf46f57ed1256c",
		Arch:          "compute_75",
		PTX:           ptxTranspose,
		RequiredBlock: 256,
		SharedBytes:   1024,
	})
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:          "WarpReduceSum",
		SourceSHA256:  "9233c16c55454e6fb5b4bf943b3953a3915fa2574dd43c43b5fabfc452ebb1ea",
		Arch:          "compute_75",
		PTX:           ptxWarpReduceSum,
		RequiredBlock: 128,
	})
}
