// Code generated by "gocuda generate"; DO NOT EDIT.

package prebuilt

import (
	_ "embed"

	"github.com/CWBudde/gocuda/simt"
)

// Classify reports that the kernel of that name lowered to CUDA C.
const Classify Lowered = "Classify"

// FIR reports that the kernel of that name lowered to CUDA C.
const FIR Lowered = "FIR"

// VecAdd reports that the kernel of that name lowered to CUDA C.
const VecAdd Lowered = "VecAdd"

// Magnitude reports that the kernel of that name lowered to CUDA C.
const Magnitude Lowered = "Magnitude"

// Scale reports that the kernel of that name lowered to CUDA C.
const Scale Lowered = "Scale"

//go:embed Classify.compute_75.ptx
var ptxClassify []byte

//go:embed FIR.compute_75.ptx
var ptxFIR []byte

//go:embed VecAdd.compute_75.ptx
var ptxVecAdd []byte

//go:embed Magnitude.compute_75.ptx
var ptxMagnitude []byte

//go:embed Scale.compute_75.ptx
var ptxScale []byte

func init() {
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:         "Classify",
		SourceSHA256: "429f5a395a1ce94ac51f234d80233a1eee0db124a462d28b3a9b84653895dfc8",
		Arch:         "compute_75",
		PTX:          ptxClassify,
	})
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:          "FIR",
		SourceSHA256:  "2f63dc9c83677287b49d35709334d694d26082261948e92c3f4183325466c4b3",
		Arch:          "compute_75",
		PTX:           ptxFIR,
		RequiredBlock: 256,
		SharedBytes:   1280,
	})
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:         "VecAdd",
		SourceSHA256: "683f2a741de7218bc7982b927b905a8faf58c2aaf4dda842502848ae90e405bb",
		Arch:         "compute_75",
		PTX:          ptxVecAdd,
	})
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:         "Magnitude",
		SourceSHA256: "0208c6b9cb59e380875cf5dc98a219aed0011a716bf1c51774562d5832d092a8",
		Arch:         "compute_75",
		PTX:          ptxMagnitude,
	})
	simt.RegisterPrebuilt(simt.Prebuilt{
		Name:         "Scale",
		SourceSHA256: "d1d7367069cb2aa540f2ec71543d5a06e9c750d56ba32d3a925e4a5b80c29911",
		Arch:         "compute_75",
		PTX:          ptxScale,
	})
}
