// generated by github.com/CWBudde/simtgo/simt from transpose.go
extern "C" __global__ void Transpose(float* __restrict__ out, int out_len, const float* __restrict__ in, int in_len, int w, int h)
{
	__shared__ float tile[256];
	int tx = (int)threadIdx.x;
	int ty = (int)threadIdx.y;
	int x = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	int y = (int)(blockIdx.y * blockDim.y + threadIdx.y);
	if (x < (int)(w) && y < (int)(h))
	{
		tile[(int)((unsigned int)(ty) * 16u + (unsigned int)(tx))] = in[(int)((unsigned int)(y) * (unsigned int)((int)(w)) + (unsigned int)(x))];
	}
	__syncthreads();
	int ox = (int)((unsigned int)((int)blockIdx.y) * 16u + (unsigned int)(tx));
	int oy = (int)((unsigned int)((int)blockIdx.x) * 16u + (unsigned int)(ty));
	if (ox < (int)(h) && oy < (int)(w))
	{
		out[(int)((unsigned int)(oy) * (unsigned int)((int)(h)) + (unsigned int)(ox))] = tile[(int)((unsigned int)(tx) * 16u + (unsigned int)(ty))];
	}
}
