// generated by github.com/CWBudde/gocuda/simt from transpose.go
extern "C" __global__ void Transpose(float* out, int out_len, float* in, int in_len, int w, int h)
{
	__shared__ float tile[256];
	int tx = (int)threadIdx.x;
	int ty = (int)threadIdx.y;
	int x = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	int y = (int)(blockIdx.y * blockDim.y + threadIdx.y);
	if (x < (int)(w) && y < (int)(h))
	{
		tile[ty * 16 + tx] = in[y * (int)(w) + x];
	}
	__syncthreads();
	int ox = (int)blockIdx.y * 16 + tx;
	int oy = (int)blockIdx.x * 16 + ty;
	if (ox < (int)(h) && oy < (int)(w))
	{
		out[oy * (int)(h) + ox] = tile[tx * 16 + ty];
	}
}
