// generated by github.com/CWBudde/gocuda/simt from gray.go
extern "C" __global__ void Gray(unsigned char* __restrict__ out, int out_len, const unsigned char* __restrict__ rgb, int rgb_len)
{
	int i = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	if (i >= out_len)
	{
		return;
	}
	int j = i * 3;
	if (j + 2 >= rgb_len)
	{
		return;
	}
	int r = (int)(rgb[j]);
	int g = (int)(rgb[j + 1]);
	int b = (int)(rgb[j + 2]);
	int y = 77 * r + 150 * g + 29 * b + 128 >> 8;
	out[i] = (unsigned char)(y);
}
