// generated by github.com/CWBudde/gocuda/simt from histogram.go
extern "C" __global__ void Histogram(int* bins, int bins_len, int* x, int x_len)
{
	__shared__ int tile[256];
	for (int k = (int)threadIdx.x; k < 256; k += (int)blockDim.x)
	{
		tile[k] = 0;
	}
	__syncthreads();
	int i = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	if (i < x_len)
	{
		int v = (int)(x[i]);
		if (v >= 0 && v < 256)
		{
			atomicAdd(&tile[v], 1);
		}
	}
	__syncthreads();
	for (int k = (int)threadIdx.x; k < 256; k += (int)blockDim.x)
	{
		int c = tile[k];
		if (c != 0 && k < bins_len)
		{
			atomicAdd(&bins[k], c);
		}
	}
}
