// generated by github.com/CWBudde/simtgo/simt from kernels.go
extern "C" __global__ void Magnitude(float* __restrict__ mag, int mag_len, const float* __restrict__ re, int re_len, const float* __restrict__ im, int im_len)
{
	int i = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	if (i < mag_len)
	{
		mag[i] = hypotf(re[i], im[i]);
	}
}
