// generated by github.com/CWBudde/gocuda/simt from quantize.go
extern "C" __global__ void Quantize(int* __restrict__ code, int code_len, long long* __restrict__ energy, int energy_len, bool* __restrict__ clipped, int clipped_len, const float* __restrict__ x, int x_len, float step, unsigned int seed)
{
	int i = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	if (i >= code_len)
	{
		return;
	}
	unsigned int h = seed ^ (unsigned int)(i);
	h = h * 2654435761u + 1u;
	h ^= h >> 15;
	float jitter = (float)((int)(h % 1024u)) / 1024.0f - 0.5f;
	int q = (int)(x[i] / step + jitter);
	if (q > 127)
	{
		q = 127;
		clipped[i] = true;
	}
	else
	if (q < -128)
	{
		q = -128;
		clipped[i] = true;
	}
	else
	{
		clipped[i] = false;
	}
	code[i] = q;
	energy[i] = (long long)((unsigned long long)((long long)(q)) * (unsigned long long)((long long)(q)));
}
