// generated by github.com/CWBudde/gocuda/simt from kernels.go
extern "C" __global__ void Scale(float* __restrict__ y, int y_len, const float* __restrict__ x, int x_len, float k)
{
	int i = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	if (i < y_len)
	{
		y[i] = k * x[i];
	}
}
