// generated by github.com/CWBudde/gocuda/simt from kernels.go
extern "C" __global__ void Scale(float* y, int y_len, float* x, int x_len, float k)
{
	int i = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	if (i < y_len)
	{
		y[i] = (k * x[i]);
	}
}
