// generated by github.com/CWBudde/simtgo/simt from softclip.go
__device__ float softclip(float v, float threshold);

__device__ float softclip(float v, float threshold)
{
	float a = fabsf(v);
	if (a <= threshold)
	{
		return v;
	}
	float over = a - threshold;
	float shaped = threshold + over / (1.0f + over);
	if (v < 0.0f)
	{
		return -shaped;
	}
	return shaped;
}

extern "C" __global__ void Softclip(float* __restrict__ y, int y_len, const float* __restrict__ x, int x_len, float threshold)
{
	int i = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	if (i < y_len)
	{
		y[i] = softclip(x[i], threshold);
	}
}
