// generated by github.com/CWBudde/simtgo/simt from kernels.go
extern "C" __global__ void VecAdd(float* __restrict__ c, int c_len, const float* __restrict__ a, int a_len, const float* __restrict__ b, int b_len)
{
	int i = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	if (i < c_len)
	{
		c[i] = a[i] + b[i];
	}
}
