// generated by github.com/CWBudde/gocuda/simt from kernels.go
extern "C" __global__ void VecAdd(float* c, int c_len, float* a, int a_len, float* b, int b_len)
{
	int i = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	if (i < c_len)
	{
		c[i] = (a[i] + b[i]);
	}
}
