// generated by github.com/CWBudde/gocuda/simt from warpreduce.go
extern "C" __global__ void WarpReduceSum(float* __restrict__ out, int out_len, const float* __restrict__ x, int x_len)
{
	int i = (int)(blockIdx.x * blockDim.x + threadIdx.x);
	float v = 0.0f;
	if (i < x_len)
	{
		v = x[i];
	}
	for (int off = 16; off > 0; off /= 2)
	{
		v += __shfl_down_sync(0xffffffff, v, off);
	}
	if ((int)((threadIdx.x + blockDim.x * (threadIdx.y + blockDim.y * threadIdx.z)) % 32) == 0)
	{
		int w = i / 32;
		if (w < out_len)
		{
			out[w] = v;
		}
	}
}
