package tile

import (
	"fmt"
	"strconv"
	"strings"
)

// generate lowers a graph into a single kernel.
//
// Elementwise nodes never become temporaries: they are folded into one C
// expression evaluated at the thread's index. Windowed nodes cannot be, since
// they read a neighbourhood, so each one stages a shared tile -- including the
// halo, computed through the very same fused expression -- and leaves its
// result in a local variable.
func generate(root *node) (src string, inputs []*node) {
	g := &generator{
		pname: map[*node]string{},
		local: map[*node]string{},
	}
	order := postorder(root, nil, map[*node]bool{})

	var params []string
	for _, n := range order {
		if n.kind != opInput {
			continue
		}
		name := fmt.Sprintf("p%d", len(g.inputs))
		g.pname[n] = name
		g.inputs = append(g.inputs, n)
		// const and __restrict__ for the same reason the SIMT track emits
		// them: an input is only ever read, and the launch checks the promise
		// rather than asserting it (see checkAliasing).
		params = append(params, "const float* __restrict__ "+name, "int "+name+"_len")
	}

	g.line("// generated by github.com/CWBudde/simtgo/tile: %d operations fused into one kernel", len(order))
	g.line("extern \"C\" __global__ void fused(float* __restrict__ out, int out_len, %s)", strings.Join(params, ", "))
	g.line("{")
	g.ind++
	g.line("int base = (int)(blockIdx.x * blockDim.x);")
	g.line("int t = (int)threadIdx.x;")
	g.line("int i = base + t;")

	for _, n := range order {
		if n.kind == opFIR {
			g.windowed(n)
		}
	}

	g.line("")
	g.line("if (i < out_len)")
	g.line("{")
	g.ind++
	g.line("out[i] = %s;", g.expr(root, "i"))
	g.ind--
	g.line("}")
	g.ind--
	g.line("}")
	return g.buf.String(), g.inputs
}

type generator struct {
	buf    strings.Builder
	ind    int
	pname  map[*node]string
	local  map[*node]string
	inputs []*node
}

func (g *generator) line(format string, args ...any) {
	if format != "" {
		g.buf.WriteString(strings.Repeat("\t", g.ind))
	}
	fmt.Fprintf(&g.buf, format, args...)
	g.buf.WriteByte('\n')
}

// windowed emits the shared-memory staging and tap loop for a FIR node.
func (g *generator) windowed(n *node) {
	signal, taps := n.args[0], n.args[1]
	h := g.pname[taps]
	tile := fmt.Sprintf("tile%d", n.id)
	count := fmt.Sprintf("taps%d", n.id)
	acc := fmt.Sprintf("v%d", n.id)

	g.line("")
	g.line("// windowed operation %d: stage a tile plus its halo", n.id)
	g.line("int %s = %s_len;", count, h)
	g.line("__shared__ float %s[%d];", tile, BlockSize+MaxTaps)
	g.line("for (int k = t; k < (int)blockDim.x + %s - 1; k += (int)blockDim.x)", count)
	g.line("{")
	g.ind++
	g.line("int src = base + k - (%s - 1);", count)
	g.line("%s[k] = (src >= 0 && src < out_len) ? %s : 0.0f;", tile, g.expr(signal, "src"))
	g.ind--
	g.line("}")
	g.line("__syncthreads();")
	g.line("float %s = 0.0f;", acc)
	g.line("for (int k = 0; k < %s; k++)", count)
	g.line("{")
	g.ind++
	g.line("%s += %s[k] * %s[t + %s - 1 - k];", acc, h, tile, count)
	g.ind--
	g.line("}")
	g.local[n] = acc
}

// expr renders a node as a C expression evaluated at the given index.
func (g *generator) expr(n *node, idx string) string {
	if v, ok := g.local[n]; ok {
		return v
	}
	switch n.kind {
	case opInput:
		return fmt.Sprintf("%s[%s]", g.pname[n], idx)
	case opScale:
		return fmt.Sprintf("(%s * %s)", cfloat(n.scale), g.expr(n.args[0], idx))
	case opAdd:
		return fmt.Sprintf("(%s + %s)", g.expr(n.args[0], idx), g.expr(n.args[1], idx))
	case opMul:
		return fmt.Sprintf("(%s * %s)", g.expr(n.args[0], idx), g.expr(n.args[1], idx))
	case opUnary:
		return fmt.Sprintf("%s(%s)", n.cfn, g.expr(n.args[0], idx))
	case opHypot:
		return fmt.Sprintf("hypotf(%s, %s)", g.expr(n.args[0], idx), g.expr(n.args[1], idx))
	}
	// Unreachable: FIR nodes are emitted before the expression is rendered,
	// and the graph builder rejects everything else.
	return "0.0f"
}

// postorder lists a node's dependencies before the node itself, visiting each
// shared node once.
func postorder(n *node, out []*node, seen map[*node]bool) []*node {
	if seen[n] {
		return out
	}
	seen[n] = true
	for _, a := range n.args {
		out = postorder(a, out, seen)
	}
	return append(out, n)
}

func cfloat(v float32) string {
	s := strconv.FormatFloat(float64(v), 'g', -1, 32)
	if !strings.ContainsAny(s, ".eE") {
		s += ".0"
	}
	return s + "f"
}
