package hostrun

import (
	"encoding/binary"
	"fmt"
	"reflect"
	"strings"
	"unsafe"

	"github.com/CWBudde/simtgo/gpu"
	"github.com/CWBudde/simtgo/internal/lower"
)

// shim is what CUDA gives a kernel for free and a host compiler does not.
//
// It is deliberately small. Everything it defines is either a spelling the
// host has no meaning for -- __global__, __device__ -- or one of the four
// position built-ins, which become ordinary variables the driver sets before
// each call. That is the whole of the emulation: nothing here reimplements any
// arithmetic, so a number this oracle disagrees about came from the emitter
// and not from a stand-in written here.
//
// The width assertions are not decoration. Values cross as raw bytes, so a
// machine where one of them failed would have been silently comparing two
// different layouts, and Go's bool in particular is one byte by specification
// while C++'s is only one byte by convention.
const shim = `// generated by github.com/CWBudde/simtgo/internal/fuzz/hostrun -- do not edit
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <algorithm>

static_assert(sizeof(float) == 4, "simtgo hostrun: float is not 4 bytes");
static_assert(sizeof(double) == 8, "simtgo hostrun: double is not 8 bytes");
static_assert(sizeof(short) == 2, "simtgo hostrun: short is not 2 bytes");
static_assert(sizeof(int) == 4, "simtgo hostrun: int is not 4 bytes");
static_assert(sizeof(long long) == 8, "simtgo hostrun: long long is not 8 bytes");
static_assert(sizeof(bool) == 1, "simtgo hostrun: bool is not 1 byte, and Go's is");

#define __global__
#define __device__

struct uint3 { unsigned x, y, z; };
struct dim3 { unsigned x, y, z; };
static uint3 threadIdx, blockIdx;
static dim3 blockDim, gridDim;

// Go's builtin min and max lower to CUDA's bare min and max, which over two
// values of one type are std::min and std::max.
using std::min;
using std::max;

// fmin and fmax of two zeros of opposite signs are UNSPECIFIED, in C and in
// IEEE 754 alike: minNum "returns either one". The host does not even answer
// it stably -- the same expression gives -0 compiled at -O1 and +0 at -O0,
// because the compiler picks a different instruction -- and the differential
// fuzzer duly reported the difference as a mismatch.
//
// The device's answer is not open. gpu.Fmin returns -0 and gpu.Fmax returns
// +0, which NUMERICS.md records and TestFminFmaxParity asserts against real
// hardware. Pinning them here is what a shim is for: it supplies the device's
// C where the host's is free to differ, so that a disagreement in a run means
// a mistranslation rather than a tie-break nobody promised. Everything else,
// the NaN rule included, is left to the real functions.
static double simtgo_fmin(double a, double b)
{
	if (a == 0 && b == 0) { return (signbit(a) || signbit(b)) ? -0.0 : 0.0; }
	return fmin(a, b);
}

static double simtgo_fmax(double a, double b)
{
	if (a == 0 && b == 0) { return (signbit(a) && signbit(b)) ? -0.0 : 0.0; }
	return fmax(a, b);
}

static float simtgo_fminf(float a, float b)
{
	if (a == 0 && b == 0) { return (signbit(a) || signbit(b)) ? -0.0f : 0.0f; }
	return fminf(a, b);
}

static float simtgo_fmaxf(float a, float b)
{
	if (a == 0 && b == 0) { return (signbit(a) && signbit(b)) ? -0.0f : 0.0f; }
	return fmaxf(a, b);
}

// Defined after the wrappers, so that each one still reaches the real function.
#define fmin simtgo_fmin
#define fmax simtgo_fmax
#define fminf simtgo_fminf
#define fmaxf simtgo_fmaxf

// A short read or write is the transport failing, not the kernel, and the two
// must not be confusable: exit(2) with a word on stderr rather than a partial
// answer on stdout that the caller would decode as numbers.
static void simtgo_rd(void *p, size_t n)
{
	if (n != 0 && fread(p, 1, n, stdin) != n) {
		fprintf(stderr, "simtgo hostrun: short read of %zu bytes\n", n);
		exit(2);
	}
}

static void simtgo_wr(const void *p, size_t n)
{
	if (n != 0 && fwrite(p, 1, n, stdout) != n) {
		fprintf(stderr, "simtgo hostrun: short write of %zu bytes\n", n);
		exit(2);
	}
}

`

// driverSource is the shim, the generated kernel, and a main that runs it.
//
// The driver's own identifiers all carry a simtgo_ prefix, and its locals are
// numbered rather than named after the kernel's parameters. A kernel parameter
// spelled like a C++ keyword reaches the generated signature escaped -- int
// becomes int_ -- so borrowing those names would mean reimplementing the
// emitter's escaping here, badly, to save nothing.
func driverSource(u *lower.Unit, slots []slot) string {
	var b strings.Builder
	b.WriteString(shim)
	b.WriteString(u.Source)
	b.WriteString("\nint main(void)\n{\n")
	b.WriteString("\tunsigned simtgo_geom[6];\n")
	b.WriteString("\tsimtgo_rd(simtgo_geom, sizeof simtgo_geom);\n\n")

	var call []string
	for i, s := range slots {
		name := fmt.Sprintf("simtgo_a%d", i)
		if !s.param.Slice {
			fmt.Fprintf(&b, "\t%s %s;\n\tsimtgo_rd(&%s, sizeof %s);\n", s.ctype, name, name, name)
			call = append(call, name)
			continue
		}
		// The length arrives ahead of the elements so that the driver can
		// allocate: this binary is compiled once per kernel shape and run for
		// every case, so no size may be baked into it.
		//
		// A zero-length slice still gets one element of storage, because
		// calloc(0) may return a null pointer and a kernel handed one has been
		// given something Go never would. It is unreachable either way: the
		// length the kernel sees is the real one.
		fmt.Fprintf(&b, "\tint %s_len;\n\tsimtgo_rd(&%s_len, sizeof %s_len);\n", name, name, name)
		fmt.Fprintf(&b, "\t%s *%s = (%s *)calloc((size_t)(%s_len > 0 ? %s_len : 1), sizeof(%s));\n",
			s.ctype, name, s.ctype, name, name, s.ctype)
		fmt.Fprintf(&b, "\tsimtgo_rd(%s, (size_t)%s_len * sizeof(%s));\n", name, name, s.ctype)
		call = append(call, name, name+"_len")
	}

	b.WriteString("\n\tgridDim.x = simtgo_geom[0];\n\tgridDim.y = simtgo_geom[1];\n\tgridDim.z = simtgo_geom[2];\n")
	b.WriteString("\tblockDim.x = simtgo_geom[3];\n\tblockDim.y = simtgo_geom[4];\n\tblockDim.z = simtgo_geom[5];\n\n")

	// Blocks and then threads, x fastest, which is the order CUDA numbers
	// them and the order gpu.RunCPU's diagnostics use. For a kernel in scope
	// the order cannot matter -- that is most of what being in scope means --
	// so matching CUDA's costs nothing and makes a trace readable beside one
	// from the emulator.
	b.WriteString("\tfor (unsigned bz = 0; bz < gridDim.z; bz++)\n")
	b.WriteString("\tfor (unsigned by = 0; by < gridDim.y; by++)\n")
	b.WriteString("\tfor (unsigned bx = 0; bx < gridDim.x; bx++) {\n")
	b.WriteString("\t\tblockIdx.x = bx; blockIdx.y = by; blockIdx.z = bz;\n")
	b.WriteString("\t\tfor (unsigned tz = 0; tz < blockDim.z; tz++)\n")
	b.WriteString("\t\tfor (unsigned ty = 0; ty < blockDim.y; ty++)\n")
	b.WriteString("\t\tfor (unsigned tx = 0; tx < blockDim.x; tx++) {\n")
	b.WriteString("\t\t\tthreadIdx.x = tx; threadIdx.y = ty; threadIdx.z = tz;\n")
	fmt.Fprintf(&b, "\t\t\t%s(%s);\n", u.Name, strings.Join(call, ", "))
	b.WriteString("\t\t}\n\t}\n\n")

	for i, s := range slots {
		if !s.param.Slice {
			continue
		}
		name := fmt.Sprintf("simtgo_a%d", i)
		fmt.Fprintf(&b, "\tsimtgo_wr(%s, (size_t)%s_len * sizeof(%s));\n", name, name, s.ctype)
	}
	b.WriteString("\treturn 0;\n}\n")
	return b.String()
}

// encode lays out the driver's stdin: the geometry, then each parameter in
// declaration order, a slice as its length followed by its elements.
func encode(grid, block gpu.Dim, slots []slot) []byte {
	var b []byte
	for _, v := range []int{grid.X, grid.Y, grid.Z, block.X, block.Y, block.Z} {
		b = binary.LittleEndian.AppendUint32(b, uint32(v))
	}
	for _, s := range slots {
		switch {
		case s.param.Slice:
			b = binary.LittleEndian.AppendUint32(b, uint32(s.n))
			b = append(b, sliceBytes(s.val)...)
		case s.narrow:
			// SPEC.md section 3's one deliberate infidelity, applied where a
			// launch applies it: Go's int reaches the kernel as C's int.
			b = binary.LittleEndian.AppendUint32(b, uint32(int32(s.val.Int())))
		default:
			b = append(b, scalarBytes(s.val)...)
		}
	}
	return b
}

// decode copies the driver's stdout back into the caller's slices.
//
// A length mismatch is reported rather than tolerated: the driver writes
// exactly what it was given, so anything else means the two sides disagree
// about the parameter list, and a short buffer silently left half-updated is
// the kind of thing a differential test would then blame on the emitter.
func decode(name string, out []byte, slots []slot) error {
	want := 0
	for _, s := range slots {
		if s.param.Slice {
			want += s.n * s.elem
		}
	}
	if len(out) != want {
		return fmt.Errorf("hostrun: %s: the driver wrote %d bytes, want %d", name, len(out), want)
	}
	off := 0
	for _, s := range slots {
		if !s.param.Slice {
			continue
		}
		n := s.n * s.elem
		copy(sliceBytes(s.val), out[off:off+n])
		off += n
	}
	return nil
}

// sliceBytes views a slice's elements as bytes.
//
// This is the transport, and it is deliberately a view rather than a
// conversion: Go's layout for the element type is what the generated C
// declares and what static_assert pins, so there is nothing to convert. It is
// also what makes decode write into the caller's slice rather than a copy.
func sliceBytes(v reflect.Value) []byte {
	n := v.Len() * int(v.Type().Elem().Size())
	if n == 0 {
		return nil
	}
	return unsafe.Slice((*byte)(v.UnsafePointer()), n)
}

// scalarBytes copies a scalar's bytes, padding inside a struct included.
func scalarBytes(v reflect.Value) []byte {
	p := reflect.New(v.Type())
	p.Elem().Set(v)
	b := make([]byte, v.Type().Size())
	copy(b, unsafe.Slice((*byte)(p.UnsafePointer()), len(b)))
	return b
}
